/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.EmprestimoController;
import javax.swing.JOptionPane;
import model.Emprestimo;
import model.Funcionario;
import model.Livro;
import model.Usuario;
import util.Sessao;

/**
 *
 * @author joaovitor
 */
public class TelaEmprestimo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName());

    /**
     * Creates new form TelaEmprestimo
     */
    public TelaEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbSubTitulo = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbLivro = new javax.swing.JLabel();
        lbDataEmprestimo = new javax.swing.JLabel();
        lbDataDevolucao = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtLivro = new javax.swing.JTextField();
        txtDataEmprestimo = new javax.swing.JTextField();
        txtDataDevolucao = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        btRegistrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("sansserif", 1, 28)); // NOI18N
        lbTitulo.setText("LIBRARY PLUS");

        lbSubTitulo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbSubTitulo.setText("Registro de Emprestimos");

        lbUsuario.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        lbUsuario.setText("ID Usuário:");

        lbLivro.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        lbLivro.setText("ID Livro:");

        lbDataEmprestimo.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        lbDataEmprestimo.setText("Data de Empréstimo:");

        lbDataDevolucao.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        lbDataDevolucao.setText("Data de Devolução:");

        lbStatus.setFont(new java.awt.Font("sansserif", 0, 15)); // NOI18N
        lbStatus.setText("Status:");

        btRegistrar.setBackground(new java.awt.Color(51, 153, 82));
        btRegistrar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btRegistrar.setText("Registrar");
        btRegistrar.addActionListener(this::btRegistrarActionPerformed);

        btLimpar.setBackground(new java.awt.Color(255, 153, 0));
        btLimpar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(this::btLimparActionPerformed);

        btVoltar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(this::btVoltarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTitulo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDataEmprestimo)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btRegistrar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btLimpar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btVoltar)
                                    .addGap(21, 21, 21))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbLivro))
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtLivro, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbStatus)
                                        .addComponent(lbDataDevolucao)
                                        .addComponent(txtDataDevolucao)
                                        .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSubTitulo)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsuario)
                    .addComponent(lbDataDevolucao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLivro)
                    .addComponent(lbStatus))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDataEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegistrar)
                    .addComponent(btLimpar)
                    .addComponent(btVoltar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        String usuario = txtUsuario.getText().trim();
        String livro = txtLivro.getText().trim();
        String dataEm = txtDataEmprestimo.getText().trim();
        String dataDe = txtDataDevolucao.getText().trim();
        String status = txtStatus.getText().trim();
        
        if(usuario.isEmpty() 
               || livro.isEmpty() 
               || dataEm.isEmpty() 
               ||dataDe.isEmpty()
               || status.isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos");
            return;
        }
        
        int usuarioInt;
        int livroInt;
                
        try{
            usuarioInt = Integer.parseInt(usuario);
            livroInt = Integer.parseInt(livro);
        }catch(NumberFormatException erro){
            JOptionPane.showMessageDialog(this, "Os IDs precisam ser números inteiros");
            return;
        }

         Funcionario fun = Sessao.getFuncionarioLogado();

         Emprestimo em = new Emprestimo();

         em.setIdUsuario(usuarioInt);
         em.setIdLivro(livroInt);
         em.setIdFuncionario(fun.getId());
         em.setDataEmprestimo(dataEm);
         em.setDataDevolucao(dataDe);
         em.setStatus(status);

         EmprestimoController controller = new EmprestimoController();

         try {
             controller.registrarEmprestimo(em);

             JOptionPane.showMessageDialog(this, "Empréstimo salvo com sucesso!");

             txtUsuario.setText("");
             txtLivro.setText("");
             txtDataEmprestimo.setText("");
             txtDataDevolucao.setText("");
             txtStatus.setText("");
             txtUsuario.requestFocus();

         } catch (IllegalArgumentException erro) {
             JOptionPane.showMessageDialog(this, erro.getMessage());
         }
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtUsuario.setText("");
        txtLivro.setText("");
        txtDataEmprestimo.setText("");
        txtDataDevolucao.setText("");
        txtStatus.setText("");
        txtUsuario.requestFocus();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        TelaMenu menu = new TelaMenu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEmprestimo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDataDevolucao;
    private javax.swing.JLabel lbDataEmprestimo;
    private javax.swing.JLabel lbLivro;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbSubTitulo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JTextField txtDataDevolucao;
    private javax.swing.JTextField txtDataEmprestimo;
    private javax.swing.JTextField txtLivro;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
