/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import util.Sessao;

/**
 *
 * @author joaovitor
 */
public class TelaMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenu.class.getName());

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbSubTitulo = new javax.swing.JLabel();
        mbMenu = new javax.swing.JMenuBar();
        mArquivo = new javax.swing.JMenu();
        mtEncerrar = new javax.swing.JMenuItem();
        mtSair = new javax.swing.JMenuItem();
        mCadastro = new javax.swing.JMenu();
        mtLivro = new javax.swing.JMenuItem();
        mtFuncionario = new javax.swing.JMenuItem();
        mConsulta = new javax.swing.JMenu();
        mtListaLivro = new javax.swing.JMenuItem();
        mtListaUsuario = new javax.swing.JMenuItem();
        mtListaFuncionario = new javax.swing.JMenuItem();
        mtListaEmprestimo = new javax.swing.JMenuItem();
        mEmprestimo = new javax.swing.JMenu();
        mtEmprestimo = new javax.swing.JMenuItem();
        mtDevolucao = new javax.swing.JMenuItem();
        mRelatorio = new javax.swing.JMenu();
        mtRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("sansserif", 1, 28)); // NOI18N
        lbTitulo.setText("LIBRARY PLUS");

        lbSubTitulo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbSubTitulo.setText("Bem- Vindo, Funcionário ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTitulo)
                    .addComponent(lbSubTitulo))
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lbTitulo)
                .addGap(32, 32, 32)
                .addComponent(lbSubTitulo)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        mArquivo.setText("Arquivo");

        mtEncerrar.setText("Encerrar sessão");
        mtEncerrar.addActionListener(this::mtEncerrarActionPerformed);
        mArquivo.add(mtEncerrar);

        mtSair.setText("Sair");
        mtSair.addActionListener(this::mtSairActionPerformed);
        mArquivo.add(mtSair);

        mbMenu.add(mArquivo);

        mCadastro.setText("Cadastros");

        mtLivro.setText("Livro");
        mtLivro.addActionListener(this::mtLivroActionPerformed);
        mCadastro.add(mtLivro);

        mtFuncionario.setText("Funcionário");
        mtFuncionario.addActionListener(this::mtFuncionarioActionPerformed);
        mCadastro.add(mtFuncionario);

        mbMenu.add(mCadastro);

        mConsulta.setText("Consultas");

        mtListaLivro.setText("Livro");
        mtListaLivro.addActionListener(this::mtListaLivroActionPerformed);
        mConsulta.add(mtListaLivro);

        mtListaUsuario.setText("Usuário");
        mtListaUsuario.addActionListener(this::mtListaUsuarioActionPerformed);
        mConsulta.add(mtListaUsuario);

        mtListaFuncionario.setText("Funcionário");
        mtListaFuncionario.addActionListener(this::mtListaFuncionarioActionPerformed);
        mConsulta.add(mtListaFuncionario);

        mtListaEmprestimo.setText("Empréstimo");
        mtListaEmprestimo.addActionListener(this::mtListaEmprestimoActionPerformed);
        mConsulta.add(mtListaEmprestimo);

        mbMenu.add(mConsulta);

        mEmprestimo.setText("Empréstimos");

        mtEmprestimo.setText("Novo Empréstimo");
        mtEmprestimo.addActionListener(this::mtEmprestimoActionPerformed);
        mEmprestimo.add(mtEmprestimo);

        mtDevolucao.setText("Devolução");
        mtDevolucao.addActionListener(this::mtDevolucaoActionPerformed);
        mEmprestimo.add(mtDevolucao);

        mbMenu.add(mEmprestimo);

        mRelatorio.setText("Relatórios");

        mtRelatorio.setText("Relatório ");
        mtRelatorio.addActionListener(this::mtRelatorioActionPerformed);
        mRelatorio.add(mtRelatorio);

        mbMenu.add(mRelatorio);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mtListaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtListaUsuarioActionPerformed
        new TelaListaUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_mtListaUsuarioActionPerformed

    private void mtListaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtListaLivroActionPerformed
        new TelaListaLivro().setVisible(true);
        dispose();
    }//GEN-LAST:event_mtListaLivroActionPerformed

    private void mtListaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtListaFuncionarioActionPerformed
        new TelaListaFuncionario().setVisible(true);
        dispose();
    }//GEN-LAST:event_mtListaFuncionarioActionPerformed

    private void mtListaEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtListaEmprestimoActionPerformed
        new TelaListaEmprestimo().setVisible(true);
        dispose();
    }//GEN-LAST:event_mtListaEmprestimoActionPerformed

    private void mtEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtEmprestimoActionPerformed
        new TelaCadastroEmprestimo().setVisible(true);
        dispose();
    }//GEN-LAST:event_mtEmprestimoActionPerformed

    private void mtRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtRelatorioActionPerformed
        new TelaRelatorio().setVisible(true);
        dispose();
    }//GEN-LAST:event_mtRelatorioActionPerformed

    private void mtEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtEncerrarActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(
            this,
            "Deseja encerrar a sessão atual?",
            "Encerrar sessão",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }

        Sessao.encerrarSessao();

        new TelaLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_mtEncerrarActionPerformed

    private void mtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtSairActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair do sistema?",
            "Sair",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }

        Sessao.encerrarSessao();
        System.exit(0);
    }//GEN-LAST:event_mtSairActionPerformed

    private void mtDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtDevolucaoActionPerformed
        new TelaListaEmprestimo().setVisible(true);
        dispose();
    }//GEN-LAST:event_mtDevolucaoActionPerformed

    private void mtLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtLivroActionPerformed
        new TelaCadastroLivro().setVisible(true);
        dispose();
    }//GEN-LAST:event_mtLivroActionPerformed

    private void mtFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtFuncionarioActionPerformed
        new TelaCadastroFuncionario().setVisible(true);
        dispose();
    }//GEN-LAST:event_mtFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbSubTitulo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JMenu mArquivo;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mConsulta;
    private javax.swing.JMenu mEmprestimo;
    private javax.swing.JMenu mRelatorio;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem mtDevolucao;
    private javax.swing.JMenuItem mtEmprestimo;
    private javax.swing.JMenuItem mtEncerrar;
    private javax.swing.JMenuItem mtFuncionario;
    private javax.swing.JMenuItem mtListaEmprestimo;
    private javax.swing.JMenuItem mtListaFuncionario;
    private javax.swing.JMenuItem mtListaLivro;
    private javax.swing.JMenuItem mtListaUsuario;
    private javax.swing.JMenuItem mtLivro;
    private javax.swing.JMenuItem mtRelatorio;
    private javax.swing.JMenuItem mtSair;
    // End of variables declaration//GEN-END:variables
}
